# Generated by Django 3.0.6 on 2020-06-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_app', '0003_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='name',
            field=models.CharField(default='Untitled', max_length=200),
        ),
    ]
