# Generated by Django 3.0.6 on 2020-07-09 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_app', '0005_art_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LospecPalette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=24)),
                ('creator', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LospecColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7)),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colors', to='pixel_app.LospecPalette')),
            ],
        ),
    ]
